<?php

namespace Database\Seeders;

use App\Models\User;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // Seed login data
        DB::table('users')->insert([
            [
                'name' => 'Thom Baker',
                'email' => 'thom@laundry.com',
                'password' => Hash::make('password'),
                'role' => 'owner',
            ],
            [
                'name' => 'Maggie Cheung',
                'email' => 'maggie@laundry.com',
                'password' => Hash::make('password'),
                'role' => 'cashier',
            ],
            [
                'name' => 'John Doe',
                'email' => 'john@laundry.com',
                'password' => Hash::make('password'),
                'role' => 'unauthorized',
            ],
        ]);

        // Seed services data
        DB::table('services')->insert([
            [
                'service_name' => 'Standard',
                'service_price' => 8000.00,
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_name' => 'Express',
                'service_price' => 10000.00,
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_name' => 'Instant',
                'service_price' => 15000.00,
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Seed laundry data
        DB::table('laundries')->insert([
            [
                'customer_name' => 'Tony Leung',
                'customer_phone_number' => '089755538123',
                'laundry_weight' => 10.00,
                'laundry_date' => now(),
                'user_id' => 1,
                'service_id' => 1,
                'status' => 'Unfinished',
                'description' => 'Regular customer, prefers express service.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_name' => 'Faye Wong',
                'customer_phone_number' => '081266662122',
                'laundry_weight' => 5.00,
                'laundry_date' => now(),
                'user_id' => 1,
                'service_id' => 2,
                'status' => 'Unfinished',
                'description' => 'First-time customer, requested standard service.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_name' => 'Brigitte Lin',
                'customer_phone_number' => '083267772899',
                'laundry_weight' => 5.00,
                'laundry_date' => now(),
                'user_id' => 1,
                'service_id' => 2,
                'status' => 'Finished',
                'description' => 'Frequent customer, prefers instant service.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_name' => 'Andy Lau',
                'customer_phone_number' => '081234567890',
                'laundry_weight' => 7.00,
                'laundry_date' => now()->subDays(10),
                'user_id' => 1,
                'service_id' => 3,
                'status' => 'Unfinished',
                'description' => 'Requested express service, urgent.',
                'created_at' => now()->subDays(10),
                'updated_at' => now()->subDays(10),
            ],
            [
                'customer_name' => 'Chow Yun-fat',
                'customer_phone_number' => '082345678901',
                'laundry_weight' => 8.00,
                'laundry_date' => now()->subDays(20),
                'user_id' => 1,
                'service_id' => 1,
                'status' => 'Finished',
                'description' => 'Regular customer, prefers standard service.',
                'created_at' => now()->subDays(20),
                'updated_at' => now()->subDays(20),
            ],
            [
                'customer_name' => 'Jet Li',
                'customer_phone_number' => '083456789012',
                'laundry_weight' => 6.00,
                'laundry_date' => now()->subDays(30),
                'user_id' => 1,
                'service_id' => 2,
                'status' => 'Unfinished',
                'description' => 'Requested instant service, urgent.',
                'created_at' => now()->subDays(30),
                'updated_at' => now()->subDays(30),
            ],
            [
                'customer_name' => 'Jackie Chan',
                'customer_phone_number' => '084567890123',
                'laundry_weight' => 9.00,
                'laundry_date' => now()->subDays(40),
                'user_id' => 1,
                'service_id' => 3,
                'status' => 'Finished',
                'description' => 'Frequent customer, prefers express service.',
                'created_at' => now()->subDays(40),
                'updated_at' => now()->subDays(40),
            ],
            [
                'customer_name' => 'Michelle Yeoh',
                'customer_phone_number' => '085678901234',
                'laundry_weight' => 4.00,
                'laundry_date' => now()->subDays(50),
                'user_id' => 1,
                'service_id' => 1,
                'status' => 'Unfinished',
                'description' => 'First-time customer, requested standard service.',
                'created_at' => now()->subDays(50),
                'updated_at' => now()->subDays(50),
            ],
            [
                'customer_name' => 'Donnie Yen',
                'customer_phone_number' => '086789012345',
                'laundry_weight' => 3.00,
                'laundry_date' => now()->subDays(60),
                'user_id' => 1,
                'service_id' => 2,
                'status' => 'Finished',
                'description' => 'Regular customer, prefers instant service.',
                'created_at' => now()->subDays(60),
                'updated_at' => now()->subDays(60),
            ],
            [
                'customer_name' => 'Tony Jaa',
                'customer_phone_number' => '087890123456',
                'laundry_weight' => 5.00,
                'laundry_date' => now()->subDays(70),
                'user_id' => 1,
                'service_id' => 3,
                'status' => 'Unfinished',
                'description' => 'Requested express service, urgent.',
                'created_at' => now()->subDays(70),
                'updated_at' => now()->subDays(70),
            ],
            [
                'customer_name' => 'Bruce Lee',
                'customer_phone_number' => '088901234567',
                'laundry_weight' => 6.00,
                'laundry_date' => now()->subDays(80),
                'user_id' => 1,
                'service_id' => 1,
                'status' => 'Finished',
                'description' => 'Frequent customer, prefers standard service.',
                'created_at' => now()->subDays(80),
                'updated_at' => now()->subDays(80),
            ],
            [
                'customer_name' => 'Sammo Hung',
                'customer_phone_number' => '089012345678',
                'laundry_weight' => 7.00,
                'laundry_date' => now()->subDays(90),
                'user_id' => 1,
                'service_id' => 2,
                'status' => 'Unfinished',
                'description' => 'First-time customer, requested instant service.',
                'created_at' => now()->subDays(90),
                'updated_at' => now()->subDays(90),
            ],
            [
                'customer_name' => 'Stephen Chow',
                'customer_phone_number' => '089123456789',
                'laundry_weight' => 8.00,
                'laundry_date' => now()->subDays(100),
                'user_id' => 1,
                'service_id' => 3,
                'status' => 'Finished',
                'description' => 'Regular customer, prefers express service.',
                'created_at' => now()->subDays(100),
                'updated_at' => now()->subDays(100),
            ],
            [
                'customer_name' => 'Gong Li',
                'customer_phone_number' => '089234567890',
                'laundry_weight' => 9.00,
                'laundry_date' => now()->subDays(110),
                'user_id' => 1,
                'service_id' => 1,
                'status' => 'Unfinished',
                'description' => 'Frequent customer, prefers standard service.',
                'created_at' => now()->subDays(110),
                'updated_at' => now()->subDays(110),
            ],
            [
                'customer_name' => 'Zhang Ziyi',
                'customer_phone_number' => '089345678901',
                'laundry_weight' => 10.00,
                'laundry_date' => now()->subDays(120),
                'user_id' => 1,
                'service_id' => 2,
                'status' => 'Finished',
                'description' => 'First-time customer, requested instant service.',
                'created_at' => now()->subDays(120),
                'updated_at' => now()->subDays(120),
            ],
        ]);

        // Seed transaction data
        DB::table('transactions')->insert([
            [
                'payment_date' => now(),
                'total_price' => 50000.00,
                'payment_status' => 'completed',
                'user_id' => 1,
                'laundry_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'payment_date' => now()->subDays(10),
                'total_price' => 70000.00,
                'payment_status' => 'completed',
                'user_id' => 1,
                'laundry_id' => 4,
                'created_at' => now()->subDays(10),
                'updated_at' => now()->subDays(10),
            ],
            [
                'payment_date' => now()->subDays(20),
                'total_price' => 80000.00,
                'payment_status' => 'pending',
                'user_id' => 1,
                'laundry_id' => 5,
                'created_at' => now()->subDays(20),
                'updated_at' => now()->subDays(20),
            ],
            [
                'payment_date' => now()->subDays(30),
                'total_price' => 60000.00,
                'payment_status' => 'completed',
                'user_id' => 1,
                'laundry_id' => 6,
                'created_at' => now()->subDays(30),
                'updated_at' => now()->subDays(30),
            ],
            [
                'payment_date' => now()->subDays(40),
                'total_price' => 90000.00,
                'payment_status' => 'pending',
                'user_id' => 1,
                'laundry_id' => 7,
                'created_at' => now()->subDays(40),
                'updated_at' => now()->subDays(40),
            ],
            [
                'payment_date' => now()->subDays(50),
                'total_price' => 40000.00,
                'payment_status' => 'completed',
                'user_id' => 1,
                'laundry_id' => 8,
                'created_at' => now()->subDays(50),
                'updated_at' => now()->subDays(50),
            ],
            [
                'payment_date' => now()->subDays(60),
                'total_price' => 30000.00,
                'payment_status' => 'pending',
                'user_id' => 1,
                'laundry_id' => 9,
                'created_at' => now()->subDays(60),
                'updated_at' => now()->subDays(60),
            ],
            [
                'payment_date' => now()->subDays(70),
                'total_price' => 50000.00,
                'payment_status' => 'completed',
                'user_id' => 1,
                'laundry_id' => 10,
                'created_at' => now()->subDays(70),
                'updated_at' => now()->subDays(70),
            ],
            [
                'payment_date' => now()->subDays(80),
                'total_price' => 60000.00,
                'payment_status' => 'pending',
                'user_id' => 1,
                'laundry_id' => 11,
                'created_at' => now()->subDays(80),
                'updated_at' => now()->subDays(80),
            ],
            [
                'payment_date' => now()->subDays(90),
                'total_price' => 70000.00,
                'payment_status' => 'completed',
                'user_id' => 1,
                'laundry_id' => 12,
                'created_at' => now()->subDays(90),
                'updated_at' => now()->subDays(90),
            ],
        ]);
    }
}
